logsBucket: 'gs://laravel-log/'

steps:
  #stage 1: Building
  - name: 'docker/compose:1.28.2'
    args: ['up', '--build', 'app']

images:
  - null:
  - 'gcr.io/test-case-2-405013/travellist/job_app:$COMMIT_SHA'