logsBucket: 'gs://laravel-log/'

steps:
  - name: 'docker/compose:1.28.2'
    args: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-case-2-405013/travellist']

images:
  - 'gcr.io/test-case-2-405013/travellist/job_app:$COMMIT_SHA'

